services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.fastapi
    ports:
      - "8000:8000"
    volumes:
      - ./chats:/app/chats
      - ./system_prompt.txt:/app/system_prompt.txt
      - ./base_system_prompt.txt:/app/base_system_prompt.txt
      - ./system_prompts:/app/system_prompts
    environment:
      - CHAT_HISTORY_DIR=/app/chats
      - SYSTEM_PROMPT_FILE=/app/system_prompt.txt
      - SYSTEM_PROMPTS_DIR=/app/system_prompts
      - API_KEY=${API_KEY}
      - RATE_LIMIT_PER_HOUR=${RATE_LIMIT_PER_HOUR:-1000}
    networks:
      - app-network

  streamlit:
    build:
      context: .
      dockerfile: Dockerfile.streamlit
    ports:
      - "8501:8501"
    depends_on:
      - api
    volumes:
      - ./base_system_prompt.txt:/app/base_system_prompt.txt
    environment:
      - API_URL=http://api:8000
      - API_KEY=${API_KEY}
    networks:
      - app-network

networks:
  app-network:
    driver: bridge 